# Generated by Django 3.2.13 on 2023-11-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('year_of_birth', models.DateField()),
                ('tg', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('about_ur_self', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
